#!name= 𝘼𝙣𝙩𝙞 𝘾𝙝𝙚𝙖𝙩 𝘿𝙚𝙩𝙚𝙘𝙩𝙞𝙤𝙣
#!desc= 𝘗𝘜𝘉𝘎 𝘔𝘰𝘣𝘪𝘭𝘦, 𝘔𝘰𝘣𝘪𝘭𝘦 𝘛𝘦𝘯𝘤𝘦𝘯𝘵 𝘎𝘢𝘮𝘦𝘴...

[Rule]
RULE-SET,https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/ruleset/reject.txt,REJECT
RULE-SET,https://raw.githubusercontent.com/bigdargon/hostsVN/master/option/hostsVN-surge-rule.conf,REJECT
RULE-SET,https://raw.githubusercontent.com/bigdargon/hostsVN/master/option/hostsVN-surge-rewrite.conf,REJECT
RULE-SET,https://raw.githubusercontent.com/bigdargon/hostsVN/master/extensions/threat/surge-rule.conf,REJECT
DOMAIN-KEYWORD,listdl,REJECT
DOMAIN-KEYWORD,anticheatexpert,REJECT
