#!name= 𝘽𝙚𝙩𝙖 (𝙉𝙤 𝙔𝙤𝙪𝙩𝙪𝙗𝙚, 𝙎𝙥𝙤𝙩𝙞𝙛𝙮)
#!desc= 𝘊𝘰𝘮𝘱𝘪𝘭𝘦𝘥 𝘣𝘺 𝘓𝘰𝘺𝘭𝘥 𝘕𝘨𝘶𝘺𝘦𝘯

[Rule]
RULE-SET,https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/ruleset/reject.txt,REJECT
RULE-SET,https://raw.githubusercontent.com/bigdargon/hostsVN/master/option/hostsVN-surge-rule.conf,REJECT
RULE-SET,https://raw.githubusercontent.com/bigdargon/hostsVN/master/option/hostsVN-surge-rewrite.conf,REJECT
RULE-SET,https://raw.githubusercontent.com/bigdargon/hostsVN/master/extensions/threat/surge-rule.conf,REJECT
RULE-SET,https://raw.githubusercontent.com/bigdargon/hostsVN/master/extensions/gambling/surge-rule.conf,REJECT
RULE-SET,https://raw.githubusercontent.com/bigdargon/hostsVN/master/option/hostsVN-surge-FB.conf,REJECT

DOMAIN-KEYWORD,listdl,REJECT
DOMAIN-KEYWORD,anticheatexpert,REJECT
SCRIPT,quic,REJECT

[Script]
𝙍𝙚𝙫𝙚𝙣𝙪𝙚𝘾𝙖𝙩 = type=http-response, pattern=^https:\/\/api\.revenuecat\.com\/.+\/(receipts$|subscribers\/[^/]+$), script-path=https://gist.githubusercontent.com/ddgksf2013/dbb1695cd96743eef18f3fac5c6fe227/raw/revenuecat.js, requires-body=true, max-size=-1, timeout=300
𝙍𝙚𝙫𝙚𝙣𝙪𝙚𝘾𝙖𝙩𝙃𝙚𝙖𝙙𝙚𝙧 = type=http-request, pattern=^https:\/\/api\.revenuecat\.com\/.+\/(receipts|subscribers), script-path=https://raw.githubusercontent.com/ddgksf2013/Scripts/master/deleteHeader.js, max-size=-1, timeout=300
𝙉𝙞𝙘𝙚𝙜𝙧𝙖𝙢 = type=http-response, pattern=^https?:\/\/nicegram\.cloud\/api\/v\d\/(ai-assistant\/purchase-list|user\/info|telegram\/auth), script-path=https://github.com/ddgksf2013/MoYu/raw/master/NicegramProCrack.js, requires-body=true, max-size=-1, timeout=300
𝘾𝙖𝙢𝙎𝙘𝙖𝙣𝙣𝙚𝙧 = type=http-response, pattern=^https:\/\/(api|api-cs)\.intsig\.net\/purchase\/cs\/query_property\?, script-path=https://github.com/ddgksf2013/dev/raw/main/CamscannerProCrack.js, requires-body=true, max-size=-1, timeout=300
𝙎𝙥𝙚𝙚𝙙𝙏𝙚𝙨𝙩𝙈𝙖𝙨𝙩𝙚𝙧 = type=http-response, pattern=^https:\/\/iap\.etm\.tech\/receipts, script-path=https://raw.githubusercontent.com/lonely0811/olsd/main/speedtest.js, requires-body=true, max-size=-1, timeout=300
𝙏𝙧𝙪𝙚𝘾𝙖𝙡𝙡𝙚𝙧 = type=http-response, pattern=^https://premium-(.+)\.truecaller\.com/v\d/(subscriptions|products\/apple), script-path=https://raw.githubusercontent.com/alonex101/shdwrckt/main/truecaller.js, requires-body=true, max-size=-1, timeout=300
𝙇𝙞𝙜𝙝𝙩𝙍𝙤𝙤𝙢 = type=http-response, pattern=^https:\/\/photos\.adobe\.io\/v2\/accounts*, script-path=https://raw.githubusercontent.com/lonely0811/Surge/main/js/lroom.js, requires-body=true, max-size=-1, timeout=300
𝘽𝙚𝙣𝙙𝙞𝙣𝙜𝙎𝙥𝙤𝙤𝙣𝙨𝘼𝙥𝙥𝙨 = type=http-response, pattern=^https?:\/\/.*\.oracle\.bendingspoonsapps\.com\/v\d\/(users\/.+|purchases\/verify), script-path=https://raw.githubusercontent.com/chxm1023/Rewrite/main/bending.js, requires-body=true, max-size=-1, timeout=300
𝙭𝘼𝙘𝙘𝙤𝙪𝙣𝙩 = type=http-request, pattern=^https?:\/\/api\.x\.com\/1\.1\/account\/settings\.json, script-path=https://raw.githubusercontent.com/Maasea/sgmodule/master/Script/SRSS/dist/srss.js
𝙭𝙃𝙖𝙣𝙙𝙡𝙚𝙧 = type=http-request, pattern=^http:\/\/s.rss\/x\/.*, script-path=https://raw.githubusercontent.com/Maasea/sgmodule/master/Script/SRSS/dist/srss.js

[MITM]
hostname = api.revenuecat.com, nicegram.cloud, ap*.intsig.net, iap.etm.tech, premium*.truecaller.com, photos.adobe.io, *.oracle.bendingspoonsapps.com, api.x.com
